### ISSUE TITLE
Hmm, I don't see a license 🔢 

### ISSUE THREAD

**Issue by godofecht** [danstronoid/Chorus-Plugin#1]
Wondering if we could use this in a commercial project of ours.

**Comment by danstronoid** [comment]
Added AGPLv3 license as this is using JUCE under AGPLv3.  This was just a fun/portfolio project, but feel free to use it if you wish.   If you do decided to use it in a commercial project, I would love to hear about it!

**Comment by godofecht** [comment]
You're a kind person!
Definitely will be using this in our commercial engine. We love the way it sounds. We'd like to be able to wrap the functionality for developers out there that might want to stack other effects onto the chorus and build their own parameter macros.

**Comment by danstronoid** [comment]
Awesome!  Glad you like it.  Send me a link at some point, it would be cool to check it out.
